<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "phlorder"
 *
 * Auto generated by Extension Builder 2018-10-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF['phlorder'] = [
    'title' => 'phlorder Bestellung',
    'description' => 'Bestellstrecke des Pharmacy-Portals: Bestellungen erfassen, Bestellnummer vergeben, Bestellmails an Apotheke und Kundin versenden, Status im Frontend anzeigen',
    'category' => 'plugin',
    'author' => 'Christian Platt',
    'author_email' => 'christian.platt@pharmaline.de',
    'state' => 'alpha',
    'version' => '13.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '13.4.0-13.4.99',
            'php' => '8.2.0-8.5.99',
            'phlusereditor' => '13.0.0-13.99.99',
            'phlqr' => '13.0.0-13.99.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
